from synth.synthesizer import Synthesizer

synth = Synthesizer()
print()
print("Tämänhetkisessä versiossa voit soittaa")
print("syntetisaattoria tietokoneesi näppäimistöllä.")
print("Koskettimet on sijoitettu näppäimistölle seuraavaan tapaan:")
print(" W E    T Y U")
print("A S D F G H J K L")
print("jossa alempri rivi on valkoiset koskettimet")
print("ja ylempi mustat.")
print("Käytössä on siis yksi oktaavi,")
print("joka alkaa C:stä ja loppuu C:hen.")
print()
synth.run()
